bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation project(':soridam-domain')
    implementation project(':soridam-common')

    implementation 'org.apache.commons:commons-collections4:4.5.0'

    // 지리 데이터 관리 도구
    implementation 'org.locationtech.jts:jts-core:1.20.0'
    implementation 'org.hibernate:hibernate-spatial:7.0.0.Final'

    //swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.8'

    // Querydsl 관련 의존성 (타입 안전한 쿼리 작성)
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'

    //spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // 데이터베이스와 상호작용 (JPA 사용)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    // webClient
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // elasticsearch
    implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch")
    implementation("co.elastic.clients:elasticsearch-java:9.0.2")

    implementation 'org.postgresql:postgresql'
}