spring:
  config:
    import: application-oicd.yml
  application:
    name: sorisoop-server

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:soridam}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: always

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  issuer: ${JWT_ISSUER}
  secret_key_string: ${JWT_SECRET_KEY_STRING}

oidc:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
